### PR TITLE
[do not merge] Add testing libraries

### PR DESCRIPTION
**Pull request by a--hoang**
# Description

[Who you added, with what permissions, and to what mailing lists.]

# Tests
I affirm that:
- [ ] The `username` field is my GitHub username
- [ ] I've double checked my email is correct
- [ ] I have 2-factor authentication turned on on my github account

### CODE REVIEW

**Comment by a--hoang** [comment]
WIP

**Comment by a--hoang** [comment]
But i also need to sleep and go to work

**Comment by lkwatson** [comment]
@KenG98 @nampham148 you guys aware of this?

**Comment by lkwatson** [comment]
Closing since things are now fixed

**Pull request closed without merging**
